// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpZ56g28QVxtV3hvBrJv1by-mbu-nTmE',
    appId: '1:187235453664:web:24d91c44d8cec8ddc15e85',
    messagingSenderId: '187235453664',
    projectId: 'billing-sample-app',
    authDomain: 'billing-sample-app.firebaseapp.com',
    storageBucket: 'billing-sample-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVA-KITkX8rGThgKsaKGwO6OfHzowo7-4',
    appId: '1:187235453664:android:7448aa4942604a62c15e85',
    messagingSenderId: '187235453664',
    projectId: 'billing-sample-app',
    storageBucket: 'billing-sample-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq6LDYOwAtiQuqoY9WmvKckHhJkr2ScnI',
    appId: '1:187235453664:ios:22e836288ac57e2dc15e85',
    messagingSenderId: '187235453664',
    projectId: 'billing-sample-app',
    storageBucket: 'billing-sample-app.appspot.com',
    iosClientId: '187235453664-d35tvgnqq11d084s0pl50pcpjbj1htad.apps.googleusercontent.com',
    iosBundleId: 'com.example.billingSampleApp',
  );
}
